version: 2.1

jobs:
  prepare:
    docker: [image: circleci/node:12]
    steps:
      - checkout
      - run: make TAG=$CIRCLE_TAG
      - persist_to_workspace:
          root: .
          paths: [pub]

  publish:
    docker: [image: circleci/python:3.6]
    environment:
      BUCKET: oas.gameye.com
    steps:
      - run: sudo pip install awscli
      - attach_workspace: { at: . }
      - run: >
          aws s3 cp
          pub/openapi.yaml
          s3://$BUCKET/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/openapi.yaml
          --content-type application/vnd.oai.openapi;version=3.0
          --cache-control 'max-age=604800'
      - run: >
          aws s3 cp
          pub/openapi.json
          s3://$BUCKET/$CIRCLE_PROJECT_REPONAME/$CIRCLE_TAG/openapi.json
          --content-type application/vnd.oai.openapi+json;version=3.0
          --cache-control 'max-age=604800'
      - run: >
          echo $CIRCLE_TAG | aws s3 cp
          -
          s3://$BUCKET/$CIRCLE_PROJECT_REPONAME/latest.txt
          --content-type text/plain
          --cache-control 'no-cache'

workflows:
  welcome:
    jobs:
      - prepare:
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - publish:
          context: authorized
          requires: [prepare]
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
