version: 2.1

jobs:
  prepare:
    docker: [image: circleci/node:12]
    steps:
      - checkout
      - run: make TAG=$CIRCLE_TAG
      - persist_to_workspace:
          root: .
          paths: [pub]

  test:
    docker: [image: circleci/node:12]
    steps:
      - checkout
      - run: ./test

  publish:
    docker: [image: circleci/python:3.6]
    environment:
      BUCKET: api-spec.gameye.com
    steps:
      - run: sudo pip install awscli
      - attach_workspace: { at: . }
      - run: >
          aws s3 cp
          pub/index.html
          s3://$BUCKET/$CIRCLE_TAG/index.html
          --content-type 'text/html'
          --cache-control 'max-age=604800'
      - run: >
          aws s3 cp
          pub/openapi.yaml
          s3://$BUCKET/$CIRCLE_TAG/openapi.yaml
          --content-type 'application/vnd.oai.openapi;version=3.0'
          --cache-control 'max-age=604800'
      - run: >
          aws s3 cp
          pub/openapi.json
          s3://$BUCKET/$CIRCLE_TAG/openapi.json
          --content-type 'application/vnd.oai.openapi+json;version=3.0'
          --cache-control 'max-age=604800'
      - run: >
          aws s3api put-bucket-website
          --bucket $BUCKET
          --website-configuration '{
            "IndexDocument": {"Suffix": "index.html"},
            "RoutingRules": [
              {
                "Condition": {"KeyPrefixEquals": "latest"},
                "Redirect": {
                  "HttpRedirectCode": "302",
                  "ReplaceKeyPrefixWith": "'$CIRCLE_TAG'"
                }
              }
            ]
          }'

workflows:
  test:
    jobs:
      - test:
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
  publish:
    jobs:
      - prepare:
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - publish:
          context: authorized
          requires: [prepare]
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v\d+\.\d+\.\d+$/ }
