version: 2.1

jobs:
  install:
    docker: [image: circleci/node:14]
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths: [node_modules]

  build:
    docker: [image: circleci/node:14]
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: make TAG=$CIRCLE_TAG PACKAGE_NAME=@gameye/$CIRCLE_PROJECT_REPONAME
      - persist_to_workspace:
          root: .
          paths: [out]

  test:
    docker: [image: circleci/node:14]
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: ./test

  publish-npm:
    docker: [image: circleci/node:14]
    steps:
      - attach_workspace: { at: . }
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: ( cd out/npm ; npm publish )

workflows:
  main:
    jobs:
      - install:
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - build:
          requires: [install]
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - test:
          requires: [install]
          filters:
            tags: { only: /^v\d+\.\d+\.\d+$/ }
      - publish-npm:
          context: authorized
          requires: [install, build]
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v\d+\.\d+\.\d+$/ }
