openapi: 3.0.3
info:
  title: Gameye Game API
  version: "0.0.0-local"
  contact:
    name: Gameye "support@gameye.com"
    email: "support@gameye.com"
    url: https://gameye.com
paths:
  /command/start-match:
    post:
      operationId: start-match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
                - gameKey
                - locationKeys
                - templateKey
                - config
              properties:
                matchKey:
                  type: string
                  minLength: 1
                  description: >
                    unique match id
                  example: "my-awesome-match"
                gameKey:
                  type: string
                  minLength: 1
                  description: >
                    game id
                  example: "csgo"
                locationKeys:
                  type: array
                  items:
                    type: string
                    minLength: 1
                    description: >
                      location id
                    example: "eu-west"
                  minItems: 1
                templateKey:
                  type: string
                  minLength: 1
                  description: >
                    template id
                  example: "esl1on1"
                config:
                  type: object
                  additionalProperties: true
                  description: >
                    "any custom parameters you want to add"
                endCallbackUrl:
                  type: string
                  minLength: 1
                  description: "URL to call when the match has ended, optional"
                  example: "https://yourbackend/matchid"
            example: |
              {
                "matchKey": "my-awesome-match"
                "gameKey": "csgo"
                "locationKeys": ["eu-west"],
                "templateKey: "esl1on1",
                "config": {
                  "map": "de_dust"
                },
                "endCallbackUrl": "https://mybackend/matchid"
              }
      responses:
        "204":
          description: >
            Match was started
          content:
            application/json:
              schema:
                type: object
                example: |
                  {
                    "id": "my-awesome-match",
                    "image": "csgo",
                    "location": "eu-west",
                    "host": "127.0.0.1",
                    "port: {
                      game: "65424"
                      query: "53423"
                    },
                    created: 1589471457344
                  }
        "401":
          description: >
            You are not authorized

  /command/stop-match:
    post:
      operationId: stop-match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
              properties:
                matchKey: { type: string, minLength: 1 }
            example: >
              {
                "matchKey": "my-awesome-match"
              }
      responses:
        "204":
          description: >
            Match was stopped
        "401":
          description: >
            You are not authorized

  /query/match:
    get:
      operationId: match
      responses:
        "200":
          description: >
            Retrieved all matches
          content:
            application/json:
              schema: {}
              example: >
                {
                  "match": {
                      "83433e65-caac-4820-b8e7-875b86dd4994": {
                          "matchKey": "83433e65-caac-4820-b8e7-875b86dd4994",
                          "gameKey": "csgo",
                          "locationKey": "eu-west",
                          "host": "127.0.0.1",
                          "created": 1588944190593,
                          "port": {
                              "game": 63857,
                              "gotv": 57599
                          }
                      }
                    }
                }
        "401":
          description: >
            You are not authorized

  /query/log:
    get:
      operationId: log
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: >
            Retrieved logs for a match
          content:
            application/json:
              schema: {}
              example: >
                {}
        "401":
          description: >
            You are not authorized

  /query/statistic:
    get:
      operationId: statistic
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: >
            Retrieved statistics for a match
          content:
            application/json:
              schema: {}
              example: >
                {}
        "401":
          description: >
            You are not authorized
