openapi: 3.0.3
info:
  title: Gameye match API specification
  version: "0.0.0-local"
paths:
  /command/start-match:
    post:
      operationId: start-match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
                - gameKey
                - locationKeys
                - templateKey
                - config
              properties:
                matchKey: { type: string, minLength: 1 }
                gameKey: { type: string, minLength: 1 }
                locationKeys:
                  type: array
                  items: { type: string, minLength: 1 }
                  minItems: 1
                templateKey: { type: string, minLength: 1 }
                config: { type: object, additionalProperties: true }
                endCallbackUrl: { type: string, minLength: 1 }
            example: >
              {}
      responses:
        "204":
          description: >
            Match was started
        "401":
          description: >
            You are not authorized

  /command/stop-match:
    post:
      operationId: stop-match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
              properties:
                matchKey: { type: string, minLength: 1 }
            example: >
              {
                "matchKey": "my-awesome-match"
              }
      responses:
        "204":
          description: >
            Match was stopped
        "401":
          description: >
            You are not authorized

  /query/match:
    get:
      operationId: match
      responses:
        "200":
          description: >
            Retrieved all matches
          content:
            application/json:
              schema: {}
              example: >
                {}
        "401":
          description: >
            You are not authorized

  /query/log:
    get:
      operationId: log
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: >
            Retrieved logs for a match
          content:
            application/json:
              schema: {}
              example: >
                {}
        "401":
          description: >
            You are not authorized

  /query/statistic:
    get:
      operationId: statistic
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: >
            Retrieved statistics for a match
          content:
            application/json:
              schema: {}
              example: >
                {}
        "401":
          description: >
            You are not authorized
