openapi: 3.0.0

info:
  title: Game API
  version: "0.0.0-local"
  contact:
    name: Gameye "support@gameye.com"
    email: "support@gameye.com"
    url: https://gameye.com

servers:
  - url: https://api.gameye.com

security:
  - api-token: []

paths:
  /command/start-match:
    post:
      operationId: start-match
      tags: ["game"]
      summary: "Create match"
      description: |
        Create a new on-demand game server
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
                - gameKey
                - locationKeys
                - templateKey
                - config
              properties:
                matchKey:
                  type: string
                  minLength: 1
                  description: |
                    unique match id
                  example: "my-awesome-match"
                gameKey:
                  type: string
                  minLength: 1
                  description: |
                    game id
                  example: "csgo"
                locationKeys:
                  type: array
                  items:
                    type: string
                    minLength: 1
                    example: "eu-west"
                  minItems: 1
                  description: |
                    location id
                templateKey:
                  type: string
                  minLength: 1
                  description: |
                    template id
                  example: "esl1on1"
                config:
                  type: object
                  additionalProperties: true
                  description: |
                    any custom parameters you want to add
                endCallbackUrl:
                  type: string
                  minLength: 1
                  description: "URL to call when the match has ended, optional"
                  example: "https://yourbackend/matchid"
            example: |
              {
                "matchKey": "my-awesome-match"
                "gameKey": "csgo"
                "locationKeys": ["eu-west"],
                "templateKey: "esl1on1",
                "config": {
                  "map": "de_dust"
                },
                "endCallbackUrl": "https://mybackend/matchid"
              }
      responses:
        "200":
          description: |
            Match was started
          content:
            application/json:
              schema:
                type: object
              example: |
                {
                  "id": "my-awesome-match",
                  "image": "csgo",
                  "location": "eu-west",
                  "host": "127.0.0.1",
                  "port: {
                    game: "65424"
                    query: "53423"
                  },
                  created: 1589471457344
                }
        "400":
          description: |
            Bad request
        "401":
          description: |
            You are not authorized
        "503":
          description: |
            Location temporary out of capacity 

  /command/stop-match:
    post:
      operationId: stop-match
      tags: ["game"]
      summary: "Stop a match"
      description: |
        Force shutdown the game server

        > 📘 Important
        > 
        > Depending on the game server it can take up to 20 seconds before the shutdown is completed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - matchKey
              properties:
                matchKey: { type: string, minLength: 1 }
            example: |
              {
                "matchKey": "my-awesome-match"
              }
      responses:
        "204":
          description: |
            Match was stopped
        "401":
          description: |
            You are not authorized
        "404":
          description: |
            Match was not found

  /query/match:
    get:
      operationId: get-matches
      tags: ["game"]
      tags: ["Get Matches"]
      summary: "Get matches"
      description: |
        Fetch a list of all active sessions
      responses:
        "200":
          description: |
            Retrieved all matches
          content:
            application/json:
              schema: {}
              example: |
                {
                  "match": {
                    "83433e65-caac-4820-b8e7-875b86dd4994": {
                      "matchKey": "83433e65-caac-4820-b8e7-875b86dd4994",
                      "gameKey": "csgo",
                      "locationKey": "eu-west",
                      "host": "127.0.0.1",
                      "created": 1588944190593,
                      "port": {
                        "game": 63857,
                        "gotv": 57599
                      }
                    },
                    "76ffc16c-6b0b-4d55-bf8d-ae74b6d962ae": {
                      "matchKey": "76ffc16c-6b0b-4d55-bf8d-ae74b6d962ae",
                      "gameKey": "shooter-game",
                      "locationKey": "us-central",
                      "host": "192.168.1.1",
                      "created": 1583164808454,
                      "port": {
                        "game": 56900,
                        "query": 53912
                      }
                    }
                  }
                }
        "401":
          description: |
            You are not authorized

  /query/log:
    get:
      operationId: log
      tags: ["game"]
      summary: "Get logs"
      description: |
        Fetch the console log output of the game server
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: |
            Retrieved logs for a match
          content:
            application/json:
              schema: {}
              example: |
                {
                  "3": {
                    "lineKey": 3,
                    "payload": "Server will auto-restart if there is a crash.\r"
                  },
                  "4": {
                      "lineKey": 4,
                      "payload": "LD_LIBRARY_PATH=/home/steam/csgo/bin:/home/steam/csgo:/home/steam/csgo/bin:\r"
                  },
                  "5": {
                      "lineKey": 5,
                      "payload": "#\r"
                  },
                  "6": {
                      "lineKey": 6,
                      "payload": "#Console initialized.\r"
                  }
                }
        "401":
          description: |
            You are not authorized
        "404":
          description: |
            Match was not found

  /query/statistic:
    get:
      operationId: statistic
      tags: ["game"]
      summary: "Get statistics"
      description: |
        Fetch team and player statistics of the match

        > 📘 Important
        > 
        > Statistics are disabled by default, please contact our support department if you would like to expose statistics of your game. 
        > The stats are only availble post-match unless you connect via our realtime API, which is available on a request basis.
      parameters:
        - name: matchKey
          in: query
          required: true
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: |
            Retrieved statistics for a match
          content:
            application/json:
              schema: {}
              example: |
                {
                  "statistic": {
                      "start": 1582898480000,
                      "stop": 1582899086000,
                      "startedRounds": 6,
                      "finishedRounds": 6,
                      "player": {
                          "3": {
                              "connected": false,
                              "playerKey": "3",
                              "uid": "BOT",
                              "name": "Brad",
                              "statistic": {
                                  "assist": 0,
                                  "death": 5,
                                  "kill": 3
                              }
                          }
                          "5": {
                              "connected": false,
                              "playerKey": "5",
                              "uid": "BOT",
                              "name": "Wayne",
                              "statistic": {
                                  "assist": 1,
                                  "death": 3,
                                  "kill": 5
                              }
                          }
                      },
                      "team": {
                          "1": {
                              "teamKey": "1",
                              "name": "Counter Terrorists",
                              "statistic": {
                                  "score": 3
                              },
                              "player": {
                                  "3": true
                              }
                          },
                          "2": {
                              "teamKey": "2",
                              "name": "Terrorists",
                              "statistic": {
                                  "score": 3
                              },
                              "player": {
                                  "5": true
                              }
                          }
                        }
                    }
                }
        "401":
          description: |
            You are not authorized
        "404":
          description: |
            Match was not found

  /query/artifacts:
    get:
      operationId: artifacts
      tags: ["game"]
      summary: "Get artifacts"
      description: |
        Start download of an artifact

        ## Providing the path parameter
        The path should be an absolute Linux path to a specific file or folder.

        Example:
        /home/{user}/{game-folder-name}/crashdump.log

        ## Downloading the artefact
        When you fetch the artifact a download of .tar.gz archive will be started that contains your requested file or folder. Please limit your download in size to a maximum of 100mb.

        > 📘 Important
        > 
        > Please note that the artifact is only available for download post-match and will be downloaded directly from the container itself.
      parameters:
        - name: session
          in: query
          required: true
          description: |
            Match ID
          schema: { type: string, minLength: 1 }
        - name: path
          in: query
          required: true
          description:  |
            local container path to the file or folder you want to download
          schema: { type: string, minLength: 1 }
      responses:
        "200":
          description: |
            Downloading artifact in the .tar format
          content:
            application/octet-stream: {}
        "401":
          description: |
            You are not authorized
        "404":
          description: |
            Match was not found

components:
  securitySchemes:
    api-token:
      type: http
      scheme: bearer
      bearerFormat: token

externalDocs:
  url: https://docs.gameye.com

x-explorer-enabled: false
x-proxy-enabled: false
x-samples-enabled: true
